apiVersion: v2
name: pagopa-afm-calculator
description: Microservice that handles calculation for pagoPA Advanced Fees Management
type: application
version: 0.39.0
appVersion: 1.1.8-2-PAGOPA-2367-ingestion-trace-execution
dependencies:
  - name: microservice-chart
    version: 5.9.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
