apiVersion: v2
name: pagopa-afm-calculator
description: Microservice that handles calculation for pagoPA Advanced Fees Management
type: application
version: 0.65.0
appVersion: 1.2.17-3-ingestion-2023
dependencies:
  - name: microservice-chart
    version: 5.9.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
