apiVersion: v2
name: pagopa-biz-pm-ingestion
description: Micro-Service to ingest transaction from PM to BIZ Events
type: application
version: 0.66.0
appVersion: 1.2.18
dependencies:
  - name: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
