apiVersion: v2
name: pagopa-afm-calculator
description: Microservice that handles calculation for pagoPA Advanced Fees Management
type: application
version: 0.9.0
appVersion: 0.0.1-9-PAGOPA-1647-pm-ingestion
dependencies:
  - name: microservice-chart
    version: 5.9.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
