microservice-chart:
  namespace: "bizevents"
  nameOverride: ""
  fullnameOverride: "pagopa-biz-pm-ingestion"
  image:
    repository: ghcr.io/pagopa/pagopa-biz-pm-ingestion
    tag: "1.2.17-2-ingestion-2023"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuprod.bizevents.internal.platform.pagopa.it"
    path: /pagopa-biz-pm-ingestion/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - all
  resources:
    requests:
      memory: "2048Mi"
      cpu: "1.0"
    limits:
      memory: "4096Mi"
      cpu: "2.5"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    ENV: 'prod'
    WEBSITE_SITE_NAME: 'pagopabizpmingestion'
    APP_LOGGING_LEVEL: 'INFO'
    DEFAULT_LOGGING_LEVEL: 'WARN'
    CORS_CONFIGURATION: '{"origins": ["*"], "methods": ["*"]}'
    COSMOS_DB_URI: 'https://pagopa-p-weu-bizevents-ds-cosmos-account.documents.azure.com:443/'
    COSMOS_DB_NAME: 'db'
    COSMOS_DB_CONTAINER_NAME: 'biz-events'
    COSMOS_DB_VIEW_USER_CONTAINER_NAME: 'biz-events-view-user'
    COSMOS_DB_VIEW_GENERAL_CONTAINER_NAME: 'biz-events-view-general'
    COSMOS_DB_VIEW_CART_CONTAINER_NAME: 'biz-events-view-cart'
    COSMOS_DB_PM_INGESTION_STEP_EXEC: 'biz-events-pmingestion-step-execution'
    COSMOS_QUERY_METRICS: 'false'
    ORACLE_PM_DB_USER: 'PAGOPA_READER'
    ORACLE_SCHEMA: 'AGID_USER'
    VALID_CHANNELS: 'CITTADINANZA_DIGITALE,IO_PAY'
    OTEL_SERVICE_NAME: "biz-pm-ingestion"
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=prod"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    JAVA_TOOL_OPTIONS: '-Xms768m -Xmx3072m'
    THREADS_NUMBER: '10'
    SLICES_NUMBER: '20'
  envSecret:
    # required
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-p-connection-string'
    OTEL_EXPORTER_OTLP_HEADERS: 'elastic-otl-secret-token'
    COSMOS_DB_PRIMARY_KEY: 'cosmos-p-biz-key'
    ORACLE_PM_DB_URL: 'oracle-pm-db-url'
    ORACLE_PM_DB_PWD: 'oracle-pm-db-pwd'
  keyvault:
    name: "pagopa-p-bizevents-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/pagopa-biz-pm-ingestion
        tag: "0.0.0"
        pullPolicy: Always
      envConfig: {}
      envSecret: {}
